config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :body, presence: true
  before_save :set_priority

  def set_priority
    task_count = Task.count
    self.priority = task_count + 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTodo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/index.html.erb
<div class="tasks-index">
  <div class="container">
    <h1>To Do:</h1>
    <div class="tasks-list">    
      <% @tasks.each do |task| %>
        <div class="task<% if task.completed %> completed<% end %>"><div class="priority"><%= task.priority %>. </div><%= task.body %></div>
      <% end %>
    </div>

    <%= link_to 'Add a task', new_task_path %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="tasks-new">
  <div class="container">
    <h1>Create a New Task</h1>
    
    <%= render 'form' %>

    <%= link_to 'Back', tasks_path %>
  </div>
</div>